export const fetchTemples = () => (dispatch) => {
    setTimeout(() => {
        const temples = [
            {
                id: 1,
                name: "Temple of Dawn",
                deity: "Buddha",
                address: "Bangkok, Thailand",
                imageUrl: "https://via.placeholder.com/300",
                established: 1782,
                festivals: ["Visakha Bucha Day", "Magha Puja Day"],
                timings: "Monday to Sunday: 8 AM - 6 PM",
                specialRituals: "Evening Chanting Ritual",
                architecture: "Khmer architectural style",
                dressCode: "Conservative dress required",
                facilities: ["Free Guided Tours", "Parking", "Restrooms"],
                nearbyAttractions: ["The Grand Palace", "Wat Arun"],
            },
            {
                id: 2,
                name: "Sri Venkateswara Temple",
                deity: "Vishnu",
                address: "Tirumala, Andhra Pradesh, India",
                imageUrl: "https://via.placeholder.com/300",
                established: 300,
                festivals: ["Brahmotsavam", "Vaikunta Ekadasi"],
                timings: "2:30 AM - 1:30 AM (next day)",
                specialRituals: "Suprabhatam, Thomala, Archana",
                architecture: "Dravidian architectural style",
                dressCode: "Traditional Indian wear required",
                facilities: [
                    "Accommodation",
                    "Free Meals",
                    "Parking",
                    "Restrooms",
                ],
                nearbyAttractions: ["Akasa Ganga", "Silathoranam"],
            },
            {
                id: 3,
                name: "Pura Ulun Danu Bratan",
                deity: "Shiva",
                address: "Bali, Indonesia",
                imageUrl: "https://via.placeholder.com/300",
                established: 1633,
                festivals: ["Saraswati", "Pagerwesi"],
                timings: "Monday to Sunday: 7 AM - 7 PM",
                specialRituals: "Melasti Ritual",
                architecture: "Balinese architectural style",
                dressCode: "Casual, Respectful attire required",
                facilities: ["Boat Rides", "Parking", "Restrooms"],
                nearbyAttractions: ["Botanical Gardens", "Bedugul Market"],
            },
            {
                id: 4,
                name: "Kinkaku-ji",
                deity: "Avalokitesvara",
                address: "Kyoto, Japan",
                imageUrl: "https://via.placeholder.com/300",
                established: 1397,
                festivals: ["Golden Pavilion"],
                timings: "Monday to Sunday: 9 AM - 5 PM",
                specialRituals: "Zen Meditation",
                architecture: "Japanese architectural style",
                dressCode: "Casual",
                facilities: ["Tea Gardens", "Parking", "Restrooms"],
                nearbyAttractions: ["Ryoan-ji", "Ninnaji"],
            },
            {
                id: 5,
                name: "Temple of Heaven",
                deity: "Heaven Worship",
                address: "Beijing, China",
                imageUrl: "https://via.placeholder.com/300",
                established: 1420,
                festivals: ["Chinese New Year"],
                timings: "Monday to Sunday: 6 AM - 8 PM",
                specialRituals: "Prayer for Good Harvest",
                architecture: "Chinese architectural style",
                dressCode: "Casual",
                facilities: ["Guided Tours", "Parking", "Restrooms"],
                nearbyAttractions: ["Tiananmen Square", "Forbidden City"],
            },
        ];

        dispatch({ type: "FETCH_TEMPLES", payload: temples });
    }, 1000);
};
